# Generated by Django 4.2.6 on 2023-11-01 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_bookdata_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='ratings',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
