# Generated by Django 4.2.6 on 2023-11-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_alter_bookdata_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdata',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
